### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jonathanbcarlson** [Heath123/rust-casio-docker#1]
Hi @Heath123,

I'd like to use rust-casio-docker as a reference to build for another target, arc-elf32.
However, without a license I can't use this repository.

**Comment by Heath123** [comment]
Hello, I’m not sure if build steps and small patches would be copyrightable anyway but just in case I’ve applied the CC0 license to make it effectively public domain. Keep in mind that this project isn’t finished and it stopped building for me at some point which I haven’t fixed yet, but I hope this is still useful.
